name: Deploy Backlog Time Recorder
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '17'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Build project
        run: mvn -B clean package
        working-directory: lambda
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}

      - name: Deploy
        run: cdk deploy --require-approval never
        env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
